### ISSUE TITLE
false compare 

### ISSUE THREAD

**Issue by xsser** [omichelsen/compare-versions#46]
payloads:
```
1.12.11-v20211011
1.12.11-v20211011-beta
```

Error when running:

```
compareVersions('10.1.1.v29012', '10.2.2.v29121'); // -1
Uncaught Error: Invalid argument not valid semver ('10.1.1.v29012' received)
    at validate (/Users/xsser/node_modules/compare-versions/index.js:36:13)
    at Array.forEach (<anonymous>)
    at compareVersions (/Users/xsser/node_modules/compare-versions/index.js:41:14)

```

**Comment by omichelsen** [comment]
Hey, you have two different examples:

These are valid:

```
1.12.11-v20211011
1.12.11-v20211011-beta
```

The example in your code is a different version `10.1.1.v29012` which is not valid.

```
compareVersions('10.1.1.v29012', '10.2.2.v29121') // <--- these versions are not valid semver
```
