### ISSUE TITLE
Error on certain hyphenated range '-'

### ISSUE THREAD

**Issue by artT14** [omichelsen/compare-versions#66]
Here is the error log message:
![image](https://user-images.githubusercontent.com/1378070/222886451-9827b817-6c27-4126-af33-cd0a331f236a.png)
```Uncaught Error: Invalid argument not valid semver ('-' received)
    at validateAndParse (index.js:131:15)
    at compareVersions (index.js:11:16)
    at compare (index.js:64:17)
    at satisfies (index.js:97:16)
    at index.js:90:27
    at Array.every (<anonymous>)
    at satisfies (index.js:90:14)
    at getVulnerabilityPaint (graph.js:251:7)
    at nodePaint (graph.js:271:19)
    at Object.nodeCanvasObject (graph.js:284:36)
validateAndParse @ index.js:131
compareVersions @ index.js:11
compare @ index.js:64
satisfies @ index.js:97
(anonymous) @ index.js:90
satisfies @ index.js:90
getVulnerabilityPaint @ graph.js:251
nodePaint @ graph.js:271
(anonymous) @ graph.js:284
(anonymous) @ force-graph.min.js:5
(anonymous) @ force-graph.min.js:5
tickFrame @ force-graph.min.js:5
Object.keys.forEach.i.<computed> @ force-graph.min.js:2
t @ force-graph.min.js:5
requestAnimationFrame (async)
t @ force-graph.min.js:5
init @ force-graph.min.js:5
o @ force-graph.min.js:2
i @ force-graph.min.js:2
drawVulnerabilityTree @ graph.js:280
(anonymous) @ graph.js:24
postMessage (async)
(anonymous) @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1039
onLoad @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1038
(anonymous) @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1065
load (async)
hookupOnLoadHandlers @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1059
(anonymous) @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:975
setTimeout (async)
onFrameLoaded @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:971
(anonymous) @ index.html?id=c3e4c0d0-f2d7-461a-aaf6-9ae5549d360d&origin=69c50012-63f2-42a6-88bd-170dcb44a4ed&swVersion=4&extensionId=ArtT14.npm-dependancy-graph&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:1002
```

I logged inputs to see what input caused error, Looks like the error happened on the following call: 
`satisfies("2.0.0", "2.0.0 - 2.0.3")`

I am using **compare-versions** to parse data yielded by `npm audit --json`.

Is this is an error on my end or is it an edge case that the library misses?

I thought maybe an error on my end so I wrote the following simple doc+script and I get the same error:
```
<!DOCTYPE html>
<html>
<head>
<title>Title of the document</title>
	<script src=https://unpkg.com/compare-versions/lib/umd/index.js></script>
	<script>
	  const { compareVersions, compare, satisfies, validate } = window.compareVersions
	  console.log(satisfies('2.0.0', '2.0.0 - 2.0.3'))
	</script>
</head>

<body>
	<p id="test"></p>
</body>

</html>
```
![image](https://user-images.githubusercontent.com/1378070/222886440-ffc49f11-3e67-4d73-8043-2bf4bbb89455.png)

P.S. If you would like I can debug, search, and  submit a PR for a fix

**Comment by omichelsen** [comment]
Thanks for reporting this. I have released a fix for hyphen ranges as v6.0.0-rc.2.
